### ISSUE TITLE
Unsure what is wrong

### ISSUE THREAD

**Issue by KCErb** [SmartsquareGmbH/delete-old-packages#1]
Hi there, not sure where the best place is to put this question.

First of all thanks for creating this action, I'm surprised how few delete actions there are and that they almost never support a "keep x" feature and they don't allow multiple packages and named versions. So this is perfect!

Now for the puzzling part. I have an action where I've set keep to 5 but I get the error that keep must be an integer between 1 and 20. I have another where I set the version pattern to the exact name of the version (let's say `foo-bar`) and get no matches like so:

```
Run smartsquaregmbh/delete-old-packages@v0.0.3
  with:
    keep: 10
    version-pattern: [0-9a-f]{8}
    names: node_build
  lucky_build
  app_server
    token: ***
Error: keep must be an integer between 0 and 20 (inclusive)
```

In this case the yaml that generated this output was

```yaml
      - name: clean up old versions
        uses: smartsquaregmbh/delete-old-packages@v0.0.3
        with:
          keep: 10
          # Delete all old images that look like a commit short sha
          version-pattern: "[0-9a-f]{8}"
          names: |
            node_build
            lucky_build
            app_server
```

For the other case (with the version-pattern issue) I see

```
Run smartsquaregmbh/delete-old-packages@v0.0.3
  with:
    version-pattern: foo-bar
    names: node_build
  lucky_build
  app_server
  
    token: ***
Fetching packages
No packages to delete
```

generated by
```yaml
      - name: delete branch version
        uses: smartsquaregmbh/delete-old-packages@v0.0.3
        with:
          version-pattern: '${{ steps.branch-name.outputs.branch-name }}'
          names: |
            node_build
            lucky_build
            app_server
```

which is odd since I can see plainly that my `node_build` image (for example) has a version tag of 'foo-bar'.

When I looked through your code I couldn't see any reason for these failures and I tried various things like using single quotes around values but to no avail.

Any thoughts of something I could try to help debug this?

**Comment by rubengees** [comment]
Hi, thanks for trying this action out!

`keep` not working seems to be an error of incorrect type handling, which I could reproduce in a quick test. I'll fix it shortly and release a new version :slightly_smiling_face: 

Regarding the version pattern I'll try to investigate.

**Comment by rubengees** [comment]
I have released a new version with the fix for `keep` and more logging.

Do you mind trying again and posting the output if you still see problems?

**Comment by KCErb** [comment]
Hey thanks for addressing this so quickly 😍 

Looks like the `keep` issue was resolved, but I still have no idea why it can't find my versions.

```
Run smartsquaregmbh/delete-old-packages@v0.1.0
  with:
    version-pattern: foo-bar
    names: node_build
  lucky_build
  app_server
  
    token: ***
Fetching packages
Found 3 packages (before filtering)
  app_server with 20 versions
  lucky_build with 20 versions
  node_build with 20 versions
No packages to delete

Run smartsquaregmbh/delete-old-packages@v0.1.0
  with:
    keep: 10
    version-pattern: [0-9a-f]{8}
    names: node_build
  lucky_build
  app_server
    token: ***
Fetching packages
Found 3 packages (before filtering)
  app_server with 20 versions
  lucky_build with 20 versions
  node_build with 20 versions
No packages to delete
```

In the first case I only have one image tagged with 'foo-bar'. I think the docks mentioned a default of 2 ... so perhaps that could be an issue? I should change keep to 0 in that case?

**Comment by chrisjohnson00** [comment]
@KCErb what's your version strings?  Your pattern doesn't match most versioning schemes.  It won't match x.y.z format
https://regex101.com/ is a good place to test your expressions

**Comment by KCErb** [comment]
The scheme I like to use is to tag the image twice when it is built. The first tag gives the first 8-characters of the commit sha that built the image and the second tag gives the name of the branch. Thus I can always `docker pull path/to/branch-name` and I'll get the latest image for that branch. Or I can `docker pull /path/to/commitsha` and get an image corresponding to a specific commit.

In the example above, I have a branch named `foo-bar` and hence an image tagged `foo-bar`. Yet the action doesn't find it. I also have dozens of images tagged with a commit sha and yet it finds none of those as well.

So in both the pattern and exact match case I get nothing.

I tried copying the same logic I see in the source code (i.e. using new RegExp and then using the `test` method) and I get `true` for the cases I'm looking at. So I'm really perplexed.

Maybe there's a difference between 'version' and the tag in the docker registry? From looking at "packages" they are identical but I could have some github terminology wrong here.

**Comment by chrisjohnson00** [comment]
FWIW, this works for me

```
      - uses: smartsquaregmbh/delete-old-packages@v0.1.0
        with:
          keep: 2
          # unescaped version : \d+\.\d+\.\d+-ci\.\d+
          version-pattern: "\\d+\\.\\d+\\.\\d+-ci\\.\\d+"
          names: |
            my-package-name-as-found-on-the-package-page-of-my-repo
```

I'm doing a similar thing as you where I'm publishing a build specific version, but I'm using semantic versions in the format of `x.y.x-ci.{build-number}`

Also, I wouldn't expect `foo-bar` to be matched, since it has a dash and your regex doesn't allow that, only 0-9 and a-f and only 8 characters.
You could be onto something with it being container tags, I've not used this action with containers... but I'd imagine they handle them "the same" on the GH side.

**Comment by KCErb** [comment]
Hmm, OK, I'll do a little more reading to see if I can find a difference due to images vs packages.

As for the `foo-bar` example, it's a bit confusing but I have two examples above. In the case of commits, I only want to keep the last 10, so I use that pattern. The other example tries to match `foo-bar` exactly because I know which branch I'm deleting when I close a PR. But the two are separate.

**Comment by chrisjohnson00** [comment]
> because I know which branch I'm deleting when I close a PR
Cool, gotcha... something I'll need eventually too it seem!

**Comment by chrisjohnson00** [comment]
Works fine for docker containers too:

```
      - uses: smartsquaregmbh/delete-old-packages@v0.1.0
        with:
          keep: 2
          # unescaped version : pr-\d+-.+
          version-pattern: "pr-\\d+-.+"
          names: |
            ansible-eks
```

Output
```
Run smartsquaregmbh/delete-old-packages@v0.1.0
Fetching packages
Found 1 packages (before filtering)
  ansible-eks with 20 versions
Deleting packages
  Deleting version pr-5-merge of package ansible-eks
  Deleting version pr-4-merge of package ansible-eks
  Deleting version pr-3-merge of package ansible-eks
  Deleting version pr-2-merge of package ansible-eks
  Deleting version pr-1-merge of package ansible-eks
5 packages deleted
```
