### ISSUE TITLE
Version matching string issues 

### ISSUE THREAD

**Issue by JackHowa** [SmartsquareGmbH/delete-old-packages#14]
Seeing this error `Error: Variable $version of type String! was provided invalid value` for both `version: 0.0.0-canary.b455522.20210511151909` as well as `version: "0.0.0-canary.b455522.20210511151909"`. Is this expected? let me know if I'm missing something. I'm excited for this alternative to github actions delete https://github.com/actions/delete-package-versions

```yml
- name: Delete one package
  uses: SmartsquareGmbH/delete-old-packages@v0.3.1
  with:
    version: 0.0.0-canary.b455522.20210511151909
    dry-run: true
    names: a11y-testing-block
```

I was going off of 

```yml
uses: smartsquaregmbh/delete-old-packages@v0.3.1
with:
  version: foo-bar
  names: |
    package
```

with quotation marks:
https://github.com/WPMedia/fusion-news-theme-blocks/actions/runs/832800627

without quotation marks: 
https://github.com/WPMedia/fusion-news-theme-blocks/runs/2559229760?check_suite_focus=true
