### ISSUE TITLE
 Variable $version of type String!

### ISSUE THREAD

**Issue by cricketsamya** [SmartsquareGmbH/delete-old-packages#19]
```
Run smartsquaregmbh/delete-old-packages@v0.3.1
Warning: Dry run is set. No package versions will be actually deleted.
Fetching packages
Error: Variable $version of type String! was provided invalid value
```
version value I tried were "3.2-SNAPSHOT", 3.2-SNAPSHOT, '3.2-SNAPSHOT' nothing works.

**Comment by rubengees** [comment]
Can you post (at least part of) your configuration?

**Comment by cricketsamya** [comment]
```
   uses: smartsquaregmbh/delete-old-packages@v0.3.1
        with:          
          dry-run: true        
          version: 3.2-SNAPSHOT
          names: |
```

```
   uses: smartsquaregmbh/delete-old-packages@v0.3.1
        with:          
          dry-run: true        
          version: "3.2-SNAPSHOT"
          names: |
```

```
   uses: smartsquaregmbh/delete-old-packages@v0.3.1
        with:          
          dry-run: true        
          version: '3.2-SNAPSHOT'
          names: |
```

```
uses: smartsquaregmbh/delete-old-packages@v0.3.1
        with:
          dry-run: true        
          version: ${{ github.event.inputs.delete_version }}
          names: |

```

These are all possible values gives me same error.
