### ISSUE TITLE
no package deleted in current repo

### ISSUE THREAD

**Issue by laurentleseigneur** [SmartsquareGmbH/delete-old-packages#20]
Hi,

i am using this action with package name build from a previous step that parse my `pom.xml` to retrieve package name.

```
      - name: Clean old packages - keep last 3
        uses: smartsquaregmbh/delete-old-packages@v0.3.2
        with:
          keep: 3
          names: |
            "${{ steps.pom-info.outputs.group-id }}.${{ steps.pom-info.outputs.artifact-id }}"

```

but when running this action, nothing is deleted and i have this message. whats going wrong in my setting ?

```
Run smartsquaregmbh/delete-old-packages@v0.3.2
Fetching packages
(node:1689) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Found 0 packages (before filtering)
No packages to delete
```

Regards,

Laurent
