### ISSUE TITLE
Keep N versions of specified version pattern. 

### ISSUE THREAD

**Issue by andersson09** [SmartsquareGmbH/delete-old-packages#21]
Is it possible to keep N versions of the specified version pattern rather than any version. 

**Scenario:**
I would like to delete both old release and pre-release packages. However, with the current set-up there is a possibility of losing all release packages. This would mainly be used for private packages.

Thanks!

**Comment by rubengees** [comment]
If you use a consistent versioning scheme for both types of packages, this should be possible. If you set the `version-pattern` option, only versions matching that will be considered for deletion.

Let's say your release versions look like "1.2.3" and your pre-release versions look like "1.2.3-alpha1".

Delete old release versions:

```yaml
- name: Delete release versions
  uses: smartsquaregmbh/delete-old-packages@v0.3.3
  with:
    version-pattern: "^\\d+\\.\\d+\\.\\d+$"
    names: |
      your-package
```

Delete old pre-release version:

```yaml
- name: Delete RC versions
  uses: smartsquaregmbh/delete-old-packages@v0.3.3
  with:
    version-pattern: "^\\d+\\.\\d+\\.\\d+-alpha\\d+$"
    names: |
      your-package
```

I recommend trying these with `dry-run: true` to see what would be deleted in the logs.
