### ISSUE TITLE
Question: Correct way to escape regex? 

### ISSUE THREAD

**Issue by NicolaSansom** [SmartsquareGmbH/delete-old-packages#23]
I found this project via the marketplace. 
It seems just what we are looking for; thanks a lot for your efforts.

Question
I have been trying to set up a regex which matches the following format:
`1.8.9--canary.203.7f11a0e.0`
`1.0.3-canary.23.af8d421.0`

Pre-escaping: `"^\d+\.\d+\.\d+--canary\.+.*" `

I have tried many different combinations with no joy. This is what I currently have:

```
jobs:
  block-fixup:
    runs-on: ubuntu-18.04
    steps:
      - uses: smartsquaregmbh/delete-old-packages@v0.4.0
        with:
         version-pattern: "^\\d+\\.\\d+\\.\\d+--canary\\.+.*"
         dry-run: true
         names: |
            package
```

Any pointers would be greatly appreciated!
