### ISSUE TITLE
Deleting Nuget packages not working

### ISSUE THREAD

**Issue by valentasm1** [SmartsquareGmbH/delete-old-packages#28]
Whatever i try it returns "Found 0 package(s) before filtering". What i am doing wrong?
Repository is private.

Package
WHS.Menu.Domain

```
name: Delete old packages /

on: 
  workflow_dispatch
     
jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps: 
      - name: delete
        uses: smartsquaregmbh/delete-old-packages@v0.6.0
        with:
          keep: 1
          names: WHS.Menu.Domain
```

**Comment by mlapaglia** [comment]
having same issue, unable to delete packages in the same repo, `Found 0 package(s) before filtering`

**Comment by DamianEdwards** [comment]
This used to work for me but stopped working sometime in the last few months.

**Comment by valentasm1** [comment]
I started to use different so now it works
https://github.com/actions/delete-package-versions

```
name: Delete old packages /

on:
  schedule:
     - cron: '30 3 * * *'
     
jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps: 
      - name: delete
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'My.Email.Domain'
          package-type: 'nuget'
          min-versions-to-keep: 5          
          delete-only-pre-release-versions: "true"
```
