### ISSUE TITLE
Variable $packageType of type PackageType was provided invalid value

### ISSUE THREAD

**Issue by fmir864** [SmartsquareGmbH/delete-old-packages#31]
I got above error when performing the action from my workflow;

Version 0.6.0 used

```
- name: Delete old packages
        uses: smartsquaregmbh/delete-old-packages@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: my-org
          type: nuget
          keep: 3
          names: |
            P1
            P2
```
